variable "name" {}
variable "location" {}
variable "resource_group" {}
variable  "web_vm_z1_1nif_id" {}
variable  "web_vm_z1_2nif_id" {}
variable  "web_vm_z2_1nif_id" {}
variable  "web_vm_z2_2nif_id" {}
variable "wassubnet_id" {}
variable "elb_pub_allo" {}
variable "elb_pub_sku" {}
variable "elb_ipcfg" {}
variable "elb_protocol" {}
variable "elb_path" {}
variable "elb_port" {}
variable "elb_sku" {}
variable "e_front_port" {}
variable "e_back_port" {}
variable "elb_rule_proto" {}
variable "elb_out_proto" {}
variable "allo_out_ports" {}
variable "elb_nat_rule_proto" {}
variable "elb_nat_front_port" {}
variable "elb_nat_back_port" {}
variable "ilb_sku" {}
variable "ilb_front_ip" {}
variable "ilb_pip_allo" {}
variable "ilb_probe_port" {}
variable "ilb_rule_front_port" {}
variable "ilb_rule_back_port" {}
variable "ilb_rule_proto" {}
variable "web_vm_z1_1pub" {}
variable "web_vm_z1_2pub" {}
variable "web_vm_z2_1pub" {}
variable "web_vm_z2_2pub" {}