variable "db-ver" {}
variable "db-admin" {}
variable "db-admin-pw" {}
variable "db-sku-name" {}
variable "ssl-enforce" {}
variable "ssl-mb" {}
variable "resource_group" {}
variable "resource_group_location" {}
variable "db_server_name" {}
variable "db-charset" {}
variable "db-colla" {}
variable "db-fw-startip" {}
variable "db-fw-endip" {}
variable "vnet_id" {}
variable "dbsubnet_id" {}
variable "dbserver_id" {}
variable "db-pri-ser-isconnec" {}
#variable "pri_dns_id" {}
#variable "pri_dns_name" {}
variable "name" {}